export const GET_COMMENTS_BY_POST_REQUESTED = 'GET_COMMENTS_BY_POST_REQUESTED';
export const GET_COMMENTS_BY_POST_SUCCESS = 'GET_COMMENTS_BY_POST_SUCCESS';
export const GET_COMMENTS_BY_POST_ERROR = 'GET_COMMENTS_BY_POST_ERROR';

export const GET_POSTS_REQUESTED = 'GET_POSTS_REQUESTED';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const GET_POST_BY_TAG_REQUESTED = 'GET_POST_BY_TAG_REQUESTED';
export const GET_POST_BY_TAG_SUCCESS = 'GET_POST_BY_TAG_SUCCESS';

export const GET_POST_USER_REQUESTED = 'GET_POST_USER_REQUESTED';
export const GET_POST_USER_SUCCESS = 'GET_POST_USER_SUCCESS';
export const GET_POST_USER_ERROR = 'GET_POST_USER_ERROR';